### ISSUE TITLE
Instructions aren't clear

### ISSUE THREAD

**Issue by Piflyer** [GuiJordao21/Thomas#1]
Hi,
I would like to first say that this project interests me a lot. But, the instructions aren't clear. First, when making the server, the instructions say that add your Watson Discovery id in line 100. There isn't a place with the word "id" to put it in. Second, when I go to the README file in /thomas/thomas, it tells me to go to this like to setup. I don't have a w3id, so I can't view it. Lastly, I couldn't find config.js in the Thomas file, so I used the tjbot instead. It would be helpful if you could clarify the instructions a little bit. Thanks.

**Comment by GuiJordao21** [comment]
sorry for the late answer!

Lets begin. I made a mistake on the line number. You need to change line 76, not 100. About the w3id redirect, i've linked it to the wrong project, I've already fixed it. There isn't a config.js, thats very odd! tks for your feed back, I'll fix these issues and will update the readme file!

**Comment by Piflyer** [comment]
Thank you!
